-- Generated by scripts/gen-forge-seed.js — do NOT hand-edit.
-- Idempotent: re-running upserts the FORGE program in place.
BEGIN;

-- ─── FORGE program ───
INSERT INTO public.programs (id, user_id, name, description, split_type, is_default, is_public, total_weeks, target_experience)
VALUES ('00000000-0000-4f06-9000-00000000f06e', NULL, 'FORGE', '12-week PPL² periodization. Push · Pull · Legs run twice weekly. Strength days build the base. Volume days break it down.', 'PPL²', true, true, 12, 'intermediate')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  split_type = EXCLUDED.split_type,
  total_weeks = EXCLUDED.total_weeks,
  target_experience = EXCLUDED.target_experience,
  is_default = true,
  is_public = true;

-- ─── Phases ───
DELETE FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e';
INSERT INTO public.program_phases (program_id, slug, name, week_start, week_end, goal, intensity_range, rpe_target, order_index)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 'intensification', 'INTENSIFICATION', 1, 3, 'Establish true working weights on all FORGE supersets. Load increases every session.', '80–85% 1RM', '7–8', 0);
INSERT INTO public.program_phases (program_id, slug, name, week_start, week_end, goal, intensity_range, rpe_target, order_index)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 'peak', 'PEAK', 4, 7, 'Every compound pushed to 1–2 reps shy of failure. Drop sets mandatory on all isolation finishers.', '85–90% 1RM', '8–9', 1);
INSERT INTO public.program_phases (program_id, slug, name, week_start, week_end, goal, intensity_range, rpe_target, order_index)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 'overdrive', 'OVERDRIVE', 8, 10, 'Max effort. PR attempts on all five main lifts. Intensity techniques on every session.', '90–95% 1RM', '9–10', 2);
INSERT INTO public.program_phases (program_id, slug, name, week_start, week_end, goal, intensity_range, rpe_target, order_index)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 'deload', 'DELOAD', 11, 11, '50% volume, 70% intensity. Mandatory recovery week. Adaptation locks in here.', '65–70% 1RM', '5–6', 3);
INSERT INTO public.program_phases (program_id, slug, name, week_start, week_end, goal, intensity_range, rpe_target, order_index)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 'retest', 'RETEST', 12, 12, 'True 1–3RM test on all main compounds. Establish new baseline. Reload and go again heavier.', '100% — PR', '10', 4);

-- ─── Weeks ───
DELETE FROM public.program_weeks WHERE program_id = '00000000-0000-4f06-9000-00000000f06e';
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  1,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'intensification'),
  0.8,
  0.75,
  1,
  1,
  '{}'::text[],
  'First week in FORGE. Your only job is to find your true working weights. Pick a weight you can move cleanly for the top of your rep range with 1–2 reps left in the tank. Log everything. These numbers are your baseline.',
  'Establish working weights on all movements.',
  '5x3–5 @ 80% 1RM',
  'Work to RPE 7–8. Find the weights.',
  '{"bench":"Find 5x5 weight. Should feel hard but clean.","pullUp":"Add just enough weight to hit 5x5 with 1–2 reps in reserve.","squat":"Find 5x5 weight. Prioritize depth and bracing over load.","rdl":"Find 4x8 weight. The stretch should be the challenge, not the weight."}'::jsonb,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  2,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'intensification'),
  0.825,
  0.775,
  1,
  1,
  '{}'::text[],
  'Add 5lb to every main compound from Week 1. On accessories, add a rep to every set before you add weight. If you couldn''t progress a compound, stay at the same weight and focus on rep quality.',
  '+5lb all main compounds. +1 rep all accessories.',
  '5x3–5 @ 82.5% 1RM',
  'RPE 8. Add a rep everywhere you can.',
  '{"bench":"+5lb from Week 1.","pullUp":"+5lb from Week 1.","squat":"+5lb from Week 1.","rdl":"+5lb from Week 1."}'::jsonb,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  3,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'intensification'),
  0.85,
  0.8,
  1,
  1,
  ARRAY['note_near_failure']::text[],
  'Final week of Intensification. Add another 5lb to compounds. Start noting which sets are approaching true failure — this becomes your ceiling for Phase 2 planning. Accessories should be feeling heavier now.',
  '+5lb all compounds. Note failure points for Phase 2.',
  '5x3–5 @ 85% 1RM',
  'RPE 8–9. Some sets should be genuinely hard.',
  '{"bench":"+5lb from Week 2. Note how many reps in reserve you had.","pullUp":"+5lb from Week 2.","squat":"+5lb from Week 2.","rdl":"+5lb from Week 2."}'::jsonb,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  4,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'peak'),
  0.875,
  0.825,
  1,
  1,
  ARRAY['drop_sets_isolation']::text[],
  'Welcome to Peak. Drop sets are now mandatory on all isolation finishers (E groups). Every compound set should end 1–2 reps shy of absolute failure. No more coasting. If the last set doesn''t challenge you, add weight.',
  '+5lb compounds. Drop sets begin on all E group finishers.',
  '5x3–5 @ 87.5% 1RM',
  'RPE 8–9. Drop sets on all finisher exercises.',
  '{"bench":"+5lb from Week 3.","pullUp":"+5–10lb from Week 3.","squat":"+5lb from Week 3.","rdl":"+5lb from Week 3."}'::jsonb,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  5,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'peak'),
  0.875,
  0.85,
  0.9,
  1,
  ARRAY['drop_sets_isolation','compressed_rest']::text[],
  'Same compound weights as Week 4. Focus shifts to accessories — increase weight on all accessory movements and compress rest times by 15 seconds on supersets. The burn should be real.',
  'Hold compound weight. +weight on all accessories. -15s rest on supersets.',
  '5x3–5 @ 87.5% 1RM — same as W4, chase more reps',
  'RPE 9. Heavier than Week 4 on all accessories.',
  NULL,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  6,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'peak'),
  0.9,
  0.875,
  0.85,
  1,
  ARRAY['drop_sets_isolation','compressed_rest','myo_reps']::text[],
  'Bump compounds to 90%. Introduce myo-reps on all isolation supersets — after your last working set, take 3 breaths and do 5 more reps. Repeat 2–3 times. This is where the muscle grows.',
  '+5–10lb compounds. Myo-reps begin on all isolation supersets.',
  '5x3–5 @ 90% 1RM',
  'RPE 9. Myo-reps after final set of all isolation supersets.',
  NULL,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  7,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'peak'),
  0.9,
  0.9,
  0.85,
  1,
  ARRAY['drop_sets_isolation','compressed_rest','myo_reps','max_effort_last_set']::text[],
  'Final week of Peak. Hold 90% on compounds but push the LAST set of each compound to true failure — find out exactly where your ceiling is. Accessories at 90%. Every technique is firing.',
  'Hold 90% on compounds. Last set of compounds to absolute failure. Accessories push to new personal records.',
  '5x3–5 @ 90% 1RM — last set to failure',
  'RPE 9–10. Chase personal records on accessories.',
  NULL,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  8,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'overdrive'),
  0.925,
  0.9,
  0.85,
  1,
  ARRAY['drop_sets_all','rest_pause','myo_reps','max_effort_last_set']::text[],
  'OVERDRIVE starts now. 92.5% on compounds. Drop sets are no longer just for finishers — apply them to all isolation work. Introduce rest-pause on accessory compound movements (rows, incline press, leg press).',
  '+5lb all compounds. Drop sets expand to all isolation. Rest-pause on accessory compounds.',
  '5x3–5 @ 92.5% 1RM',
  'RPE 9–10. Drop sets on all isolation. Rest-pause on accessory compounds.',
  NULL,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  9,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'overdrive'),
  0.95,
  0.925,
  1,
  1,
  ARRAY['drop_sets_all','rest_pause','myo_reps','pr_attempts']::text[],
  'PR week. Bump compounds to 95%. Go for a rep PR on every main compound — if you hit 5 clean reps at 95%, that''s a new 1RM calculation. Rest times go back to full to allow maximal output. Everything else stays intense.',
  'PR attempts on all five main compounds. Rest time restored for max output.',
  '5x3–5 @ 95% 1RM — chase rep PRs',
  'RPE 9–10. All techniques active.',
  '{"bench":"Go for your heaviest 3–5 reps ever.","pullUp":"Add the most weight you''ve ever used for 3–5 clean reps.","squat":"Go for your heaviest 3–5 reps ever.","rdl":"Go for your heaviest 6–8 reps ever."}'::jsonb,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  10,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'overdrive'),
  0.925,
  0.95,
  0.85,
  1,
  ARRAY['drop_sets_all','rest_pause','myo_reps','mechanical_dropset']::text[],
  'Final Overdrive week. Compounds pull back slightly from Week 9 but every set is pushed to within 1 rep of failure. Introduce mechanical drop sets on accessories — change the exercise angle mid-set to extend the set when failure hits.',
  'Every single set within 1 rep of failure. Mechanical drop sets on key accessories.',
  '5x3–5 @ 92.5% 1RM — every set within 1 rep of failure',
  'RPE 9–10. Mechanical drop sets on key accessories.',
  NULL,
  NULL
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  11,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'deload'),
  0.65,
  0.6,
  1.2,
  0.5,
  '{}'::text[],
  'Mandatory deload. Do not skip this. 65% on compounds, 60% on accessories. Cut ALL sets by 50%. No techniques, no drop sets, no going to failure. This week is about flushing the fatigue so the adaptation from 10 weeks of work can actually lock in. You will feel strong again by Friday.',
  'Recovery. 50% volume across the board.',
  '3x3–5 @ 65% 1RM — just moving, not grinding',
  'RPE 5–6. Feel the movement, don''t challenge it.',
  NULL,
  ARRAY['Cut all sets in half across every day.','No intensity techniques of any kind.','Do not go to failure on any movement.','Sleep 8+ hours every night this week.','Prioritize protein and calories — this is when muscle is actually built.']::text[]
);
INSERT INTO public.program_weeks (program_id, week_number, phase_id, compound_load_pct, accessory_load_pct, rest_modifier, set_modifier, techniques, coach_note, progression_focus, compound_target, accessory_target, key_lifts, special_instructions)
VALUES (
  '00000000-0000-4f06-9000-00000000f06e',
  12,
  (SELECT id FROM public.program_phases WHERE program_id = '00000000-0000-4f06-9000-00000000f06e' AND slug = 'retest'),
  1,
  0.85,
  1.25,
  1,
  ARRAY['pr_test']::text[],
  'PR test week. You are going to find out exactly how strong 12 weeks of FORGE has made you. Hit a true 1–3RM on Bench, Weighted Pull-Up, Back Squat, and Romanian Deadlift. These become your new baselines. Accessories at 85% — don''t fatigue yourself before the tests.',
  'True 1–3RM test on all five main compounds.',
  'Work up to a true 1–3RM. Rest 5 min between heavy attempts.',
  'RPE 8. Just maintenance this week — save energy for the compound tests.',
  NULL,
  ARRAY['Sleep well every night this week. PRs are made the night before.','Eat at or above maintenance. This is not the week to cut calories.','After each PR, log the new number. That becomes Week 1 of your next FORGE cycle.']::text[]
);

-- ─── Day templates (workouts + workout_exercises + program_days) ───
DELETE FROM public.workout_exercises WHERE workout_id IN (SELECT id FROM public.workouts WHERE user_id IS NULL AND slug LIKE 'forge-%');
DELETE FROM public.program_days WHERE program_id = '00000000-0000-4f06-9000-00000000f06e';
DELETE FROM public.workouts WHERE user_id IS NULL AND slug LIKE 'forge-%';

-- Push · Strength
INSERT INTO public.workouts (id, user_id, name, slug, day_type, color, focus)
VALUES ('00000000-0000-4f06-9001-000000000000', NULL, 'Push · Strength', 'forge-push-strength', 'push', '#F97316', 'Chest · Shoulders · Triceps · Heavy compounds, supersets at accessories');
INSERT INTO public.program_days (program_id, day_index, workout_id)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 0, '00000000-0000-4f06-9001-000000000000');
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000000',
  (SELECT id FROM public.exercises WHERE slug = 'barbell-bench-press' LIMIT 1),
  0,
  5,
  '3-5',
  180,
  'compound',
  'Add 2.5–5lb when you hit 5x5 clean.',
  'A',
  'single',
  3,
  5,
  'reps',
  '85–90% 1RM',
  'Add 2.5–5lb when you hit 5x5 clean.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000000',
  (SELECT id FROM public.exercises WHERE slug = 'incline-db-press' LIMIT 1),
  1,
  4,
  '8-10',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'B',
  'superset',
  8,
  10,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000000',
  (SELECT id FROM public.exercises WHERE slug = 'cable-lateral-raise' LIMIT 1),
  2,
  4,
  '15-20',
  90,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'B',
  'superset',
  15,
  20,
  'reps',
  'RPE 7–8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000000',
  (SELECT id FROM public.exercises WHERE slug = 'db-seated-shoulder-press' LIMIT 1),
  3,
  4,
  '10-12',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'C',
  'superset',
  10,
  12,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000000',
  (SELECT id FROM public.exercises WHERE slug = 'face-pull' LIMIT 1),
  4,
  4,
  '15',
  90,
  'iso',
  'Keep light. Shoulder health, not ego.',
  'C',
  'superset',
  15,
  15,
  'reps',
  'RPE 6–7',
  'Keep light. Shoulder health, not ego.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000000',
  (SELECT id FROM public.exercises WHERE slug = 'close-grip-bench-press' LIMIT 1),
  5,
  3,
  '10-12',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'D',
  'superset',
  10,
  12,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000000',
  (SELECT id FROM public.exercises WHERE slug = 'cable-overhead-ext' LIMIT 1),
  6,
  3,
  '12-15',
  60,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'D',
  'superset',
  12,
  15,
  'reps',
  'RPE 7–8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000000',
  (SELECT id FROM public.exercises WHERE slug = 'rope-pushdown' LIMIT 1),
  7,
  3,
  '15',
  45,
  'iso',
  'Increase starting weight when all reps are easy.',
  'E',
  'single',
  15,
  15,
  'reps',
  'Drop 20% each mini-set. No rest between drops.',
  'Increase starting weight when all reps are easy.',
  'drop_set',
  false
);

-- Pull · Strength
INSERT INTO public.workouts (id, user_id, name, slug, day_type, color, focus)
VALUES ('00000000-0000-4f06-9001-000000000001', NULL, 'Pull · Strength', 'forge-pull-strength', 'pull', '#3B82F6', 'Back · Biceps · Rear Delts · Pull heavy, lat stretch, scapular control');
INSERT INTO public.program_days (program_id, day_index, workout_id)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 1, '00000000-0000-4f06-9001-000000000001');
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000001',
  (SELECT id FROM public.exercises WHERE slug = 'weighted-pullup' LIMIT 1),
  0,
  5,
  '3-5',
  180,
  'compound',
  'Add 5lb when you hit 5x5 clean.',
  'A',
  'single',
  3,
  5,
  'reps',
  '85–90% 1RM equivalent',
  'Add 5lb when you hit 5x5 clean.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000001',
  (SELECT id FROM public.exercises WHERE slug = 'barbell-row' LIMIT 1),
  1,
  4,
  '5-7',
  0,
  'compound',
  'Add 5lb when you hit 4x7 clean.',
  'B',
  'superset',
  5,
  7,
  'reps',
  'Heavy. Bar to lower chest.',
  'Add 5lb when you hit 4x7 clean.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000001',
  (SELECT id FROM public.exercises WHERE slug = 'machine-rear-delt-fly' LIMIT 1),
  2,
  4,
  '15-20',
  90,
  'iso',
  'Add rep each session. Weight when at top of range.',
  'B',
  'superset',
  15,
  20,
  'reps',
  'RPE 7',
  'Add rep each session. Weight when at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000001',
  (SELECT id FROM public.exercises WHERE slug = 'seated-cable-row' LIMIT 1),
  3,
  4,
  '10-12',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'C',
  'superset',
  10,
  12,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000001',
  (SELECT id FROM public.exercises WHERE slug = 'straight-arm-pulldown' LIMIT 1),
  4,
  4,
  '12-15',
  90,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'C',
  'superset',
  12,
  15,
  'reps',
  'RPE 7–8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000001',
  (SELECT id FROM public.exercises WHERE slug = 'incline-db-curl' LIMIT 1),
  5,
  3,
  '10-12',
  0,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'D',
  'superset',
  10,
  12,
  'reps',
  'RPE 8. Long head stretch is everything.',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000001',
  (SELECT id FROM public.exercises WHERE slug = 'db-hammer-curl' LIMIT 1),
  6,
  3,
  '12-15',
  60,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'D',
  'superset',
  12,
  15,
  'reps',
  'RPE 7–8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000001',
  (SELECT id FROM public.exercises WHERE slug = 'face-pull' LIMIT 1),
  7,
  3,
  '20-25',
  45,
  'iso',
  'Keep this light always.',
  'E',
  'single',
  20,
  25,
  'reps',
  'Light. Every pull day ends here.',
  'Keep this light always.',
  NULL,
  false
);

-- Legs · Posterior Chain
INSERT INTO public.workouts (id, user_id, name, slug, day_type, color, focus)
VALUES ('00000000-0000-4f06-9001-000000000002', NULL, 'Legs · Posterior Chain', 'forge-legs-posterior', 'legs', '#22C55E', 'Hamstrings · Glutes · Calves · Core · The underrated day');
INSERT INTO public.program_days (program_id, day_index, workout_id)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 2, '00000000-0000-4f06-9001-000000000002');
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'romanian-deadlift' LIMIT 1),
  0,
  4,
  '6-8',
  180,
  'compound',
  'Add 5lb when you hit 4x8 clean.',
  'A',
  'single',
  6,
  8,
  'reps',
  '85% 1RM. Own the stretch.',
  'Add 5lb when you hit 4x8 clean.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'lying-leg-curl' LIMIT 1),
  1,
  4,
  '12-15',
  0,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'B',
  'superset',
  12,
  15,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'barbell-hip-thrust' LIMIT 1),
  2,
  4,
  '15',
  90,
  'compound',
  'Add 5–10lb each week.',
  'B',
  'superset',
  15,
  15,
  'reps',
  'RPE 8. Full squeeze at top.',
  'Add 5–10lb each week.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'single-leg-rdl' LIMIT 1),
  3,
  3,
  '10',
  0,
  'compound',
  'Add rep then weight as you get stronger.',
  'C',
  'superset',
  10,
  10,
  'reps',
  'RPE 7–8 each leg',
  'Add rep then weight as you get stronger.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'reverse-hyper' LIMIT 1),
  4,
  3,
  '15',
  90,
  'iso',
  'Add light weight as movement is mastered.',
  'C',
  'superset',
  15,
  15,
  'reps',
  'RPE 6–7',
  'Add light weight as movement is mastered.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'seated-calf-raise' LIMIT 1),
  5,
  4,
  '20-25',
  0,
  'iso',
  'Add weight when hitting 4x25.',
  'D',
  'superset',
  20,
  25,
  'reps',
  'RPE 8–9. Slow and painful.',
  'Add weight when hitting 4x25.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'standing-calf-raise' LIMIT 1),
  6,
  4,
  '20',
  60,
  'iso',
  'Add weight when hitting 4x20 easily.',
  'D',
  'superset',
  20,
  20,
  'reps',
  'RPE 8',
  'Add weight when hitting 4x20 easily.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'cable-crunch' LIMIT 1),
  7,
  3,
  '20',
  0,
  'iso',
  NULL,
  'E',
  'circuit',
  20,
  20,
  'reps',
  'RPE 8',
  NULL,
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'russian-twist' LIMIT 1),
  8,
  3,
  '20',
  0,
  'iso',
  NULL,
  'E',
  'circuit',
  20,
  20,
  'reps',
  'RPE 8',
  NULL,
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000002',
  (SELECT id FROM public.exercises WHERE slug = 'ab-wheel-rollout' LIMIT 1),
  9,
  3,
  '10-15',
  60,
  'iso',
  NULL,
  'E',
  'circuit',
  10,
  15,
  'reps',
  'RPE 8–9',
  NULL,
  NULL,
  false
);

-- Push · Volume
INSERT INTO public.workouts (id, user_id, name, slug, day_type, color, focus)
VALUES ('00000000-0000-4f06-9001-000000000003', NULL, 'Push · Volume', 'forge-push-volume', 'push', '#F97316', 'Chest · Shoulders · Triceps · More reps, more sets, ego-free');
INSERT INTO public.program_days (program_id, day_index, workout_id)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 3, '00000000-0000-4f06-9001-000000000003');
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'barbell-incline-bench-press' LIMIT 1),
  0,
  4,
  '10-12',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'A',
  'superset',
  10,
  12,
  'reps',
  'RPE 8. Upper chest priority.',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'cable-crossover' LIMIT 1),
  1,
  4,
  '15',
  90,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'A',
  'superset',
  15,
  15,
  'reps',
  'RPE 7–8. Squeeze across midline.',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'db-bench-press' LIMIT 1),
  2,
  4,
  '12-15',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'B',
  'superset',
  12,
  15,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'pec-deck' LIMIT 1),
  3,
  4,
  '15-20',
  90,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'B',
  'superset',
  15,
  20,
  'reps',
  'RPE 7–8. Hold the squeeze.',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'db-arnold-press' LIMIT 1),
  4,
  4,
  '10-12',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'C',
  'superset',
  10,
  12,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'cable-lateral-raise' LIMIT 1),
  5,
  4,
  '20-25',
  90,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'C',
  'superset',
  20,
  25,
  'reps',
  'RPE 7. Constant tension.',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'ez-skull-crusher' LIMIT 1),
  6,
  3,
  '12-15',
  0,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'D',
  'superset',
  12,
  15,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'cable-pushdown-bar' LIMIT 1),
  7,
  3,
  '15-20',
  60,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'D',
  'superset',
  15,
  20,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000003',
  (SELECT id FROM public.exercises WHERE slug = 'dips-chest' LIMIT 1),
  8,
  3,
  'AMRAP',
  90,
  'compound',
  'Add weight via dip belt when hitting 15+ reps.',
  'E',
  'single',
  NULL,
  NULL,
  'reps',
  'Lean forward. Chest stretch. Go to failure every set.',
  'Add weight via dip belt when hitting 15+ reps.',
  'to_failure',
  true
);

-- Pull · Volume
INSERT INTO public.workouts (id, user_id, name, slug, day_type, color, focus)
VALUES ('00000000-0000-4f06-9001-000000000004', NULL, 'Pull · Volume', 'forge-pull-volume', 'pull', '#3B82F6', 'Back · Biceps · Traps · Volume is the driver, control every negative');
INSERT INTO public.program_days (program_id, day_index, workout_id)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 4, '00000000-0000-4f06-9001-000000000004');
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000004',
  (SELECT id FROM public.exercises WHERE slug = 'lat-pulldown-wide' LIMIT 1),
  0,
  4,
  '12-15',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'A',
  'superset',
  12,
  15,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000004',
  (SELECT id FROM public.exercises WHERE slug = 'seated-cable-row' LIMIT 1),
  1,
  4,
  '12-15',
  90,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'A',
  'superset',
  12,
  15,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000004',
  (SELECT id FROM public.exercises WHERE slug = 'single-arm-row' LIMIT 1),
  2,
  4,
  '12',
  0,
  'compound',
  'Add rep then weight as you progress.',
  'B',
  'superset',
  12,
  12,
  'reps',
  'RPE 8 each side. Full ROM.',
  'Add rep then weight as you progress.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000004',
  (SELECT id FROM public.exercises WHERE slug = 'chest-supported-row' LIMIT 1),
  3,
  4,
  '12-15',
  90,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'B',
  'superset',
  12,
  15,
  'reps',
  'RPE 8',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000004',
  (SELECT id FROM public.exercises WHERE slug = 'cable-bayesian-curl' LIMIT 1),
  4,
  4,
  '12-15',
  0,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'C',
  'superset',
  12,
  15,
  'reps',
  'RPE 8. The stretch is the point.',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000004',
  (SELECT id FROM public.exercises WHERE slug = 'db-concentration-curl' LIMIT 1),
  5,
  4,
  '12-15',
  60,
  'iso',
  'Add rep each session. Add weight at top of range.',
  'C',
  'superset',
  12,
  15,
  'reps',
  'RPE 8. Hold peak 1s.',
  'Add rep each session. Add weight at top of range.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000004',
  (SELECT id FROM public.exercises WHERE slug = 'db-shrug' LIMIT 1),
  6,
  4,
  '15-20',
  60,
  'iso',
  'Add weight when hitting 4x20 easily.',
  'D',
  'single',
  15,
  20,
  'reps',
  'RPE 7–8',
  'Add weight when hitting 4x20 easily.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000004',
  (SELECT id FROM public.exercises WHERE slug = 'face-pull' LIMIT 1),
  7,
  3,
  '25',
  45,
  'iso',
  'Keep this light always.',
  'E',
  'single',
  25,
  25,
  'reps',
  'Light. Every pull day ends here.',
  'Keep this light always.',
  NULL,
  false
);

-- Legs · Quad Dominant
INSERT INTO public.workouts (id, user_id, name, slug, day_type, color, focus)
VALUES ('00000000-0000-4f06-9001-000000000005', NULL, 'Legs · Quad Dominant', 'forge-legs-quad', 'legs', '#22C55E', 'Quads · Glutes · Calves · Core · You will thank yourself in 8 weeks');
INSERT INTO public.program_days (program_id, day_index, workout_id)
VALUES ('00000000-0000-4f06-9000-00000000f06e', 5, '00000000-0000-4f06-9001-000000000005');
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'barbell-squat' LIMIT 1),
  0,
  5,
  '3-5',
  210,
  'compound',
  'Add 5lb when you hit 5x5 clean.',
  'A',
  'single',
  3,
  5,
  'reps',
  '85–90% 1RM. Brace like your life depends on it.',
  'Add 5lb when you hit 5x5 clean.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'leg-press' LIMIT 1),
  1,
  4,
  '12-15',
  0,
  'compound',
  'Add weight each week.',
  'B',
  'superset',
  12,
  15,
  'reps',
  'RPE 8. Full ROM.',
  'Add weight each week.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'walking-lunge' LIMIT 1),
  2,
  4,
  '12',
  90,
  'compound',
  'Add weight when 4x12 feels controlled.',
  'B',
  'superset',
  12,
  12,
  'reps',
  'RPE 8 each leg',
  'Add weight when 4x12 feels controlled.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'machine-hack-squat' LIMIT 1),
  3,
  3,
  '10-12',
  0,
  'compound',
  'Add rep each session. Add weight at top of range.',
  'C',
  'superset',
  10,
  12,
  'reps',
  'RPE 8. Narrow stance, VMO focus.',
  'Add rep each session. Add weight at top of range.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'bulgarian-split-squat' LIMIT 1),
  4,
  3,
  '10',
  90,
  'compound',
  'Add weight when 3x10 each side feels controlled.',
  'C',
  'superset',
  10,
  10,
  'reps',
  'RPE 8–9 each leg. Control the descent.',
  'Add weight when 3x10 each side feels controlled.',
  NULL,
  true
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'leg-extension' LIMIT 1),
  5,
  3,
  '15-20',
  0,
  'iso',
  'Add weight when hitting 3x20 before the drop.',
  'D',
  'superset',
  15,
  20,
  'reps',
  'Drop 30% on final set. Go to failure.',
  'Add weight when hitting 3x20 before the drop.',
  'drop_set',
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'standing-calf-raise' LIMIT 1),
  6,
  3,
  '20-25',
  60,
  'iso',
  'Add weight when hitting 3x25.',
  'D',
  'superset',
  20,
  25,
  'reps',
  'RPE 8–9. Full stretch.',
  'Add weight when hitting 3x25.',
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'plank' LIMIT 1),
  7,
  3,
  '60',
  0,
  'iso',
  NULL,
  'E',
  'circuit',
  60,
  60,
  'seconds',
  '60s. No sagging. Brace the entire time.',
  NULL,
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'hanging-leg-raise' LIMIT 1),
  8,
  3,
  '15',
  0,
  'iso',
  NULL,
  'E',
  'circuit',
  15,
  15,
  'reps',
  'Controlled. No swing.',
  NULL,
  NULL,
  false
);
INSERT INTO public.workout_exercises (workout_id, exercise_id, order_index, sets, reps, rest_seconds, tag, notes, superset_group, group_type, reps_min, reps_max, rep_unit, intensity_note, progression_rule, intensity_technique, is_compound)
VALUES (
  '00000000-0000-4f06-9001-000000000005',
  (SELECT id FROM public.exercises WHERE slug = 'ab-wheel-rollout' LIMIT 1),
  9,
  3,
  '10-15',
  60,
  'iso',
  NULL,
  'E',
  'circuit',
  10,
  15,
  'reps',
  'RPE 8–9',
  NULL,
  NULL,
  false
);

INSERT INTO public.program_days (program_id, day_index, workout_id, is_rest) VALUES ('00000000-0000-4f06-9000-00000000f06e', 6, NULL, true);

COMMIT;